development:
  adapter: mysql2
  encoding: utf8
  database: skooah
  pool: 5
  username: dev
  password: nascar

production:
  adapter: mysql2
  encoding: utf8
  database: skooah_prod
  pool: 5
  username: dev
  password: nascar